### ISSUE TITLE
The titles in the Workshop is invisible in Chromium-based browsers

### ISSUE THREAD

**Issue by ardatdev** [Artado-Project/artadosearch#17]
In Firefox-based browsers:
![image](https://github.com/Artado-Project/artadosearch/assets/47920304/b446a4d6-7946-4e65-8057-68c093dfe186)

In Chromium-based browsers:
![workshop](https://github.com/Artado-Project/artadosearch/assets/47920304/8a096551-9f31-4221-93f6-ca533f9aaa3c)

The problem seems to be in [here](https://github.com/Artado-Project/artadosearch/blob/9730a1d2809475e968b4fd3a055453f10067add9/artadosearch/css/panel.css#L54). It might be caused by overflow.

**Comment by yasinldev** [comment]
Bro just delete `display:block;` line.
`
.row_info span {
            margin-right: auto;
            margin-left: auto;
            max-width: 150px;
            max-height: 20vw;
            overflow: hidden;
            text-overflow: ellipsis;
        }
`

**Comment by LinuxUsersLinuxMint** [comment]
> In Firefox-based browsers: ![image](https://user-images.githubusercontent.com/47920304/274711097-b446a4d6-7946-4e65-8057-68c093dfe186.png)
> 
> In Chromium-based browsers: ![workshop](https://user-images.githubusercontent.com/47920304/274711236-8a096551-9f31-4221-93f6-ca533f9aaa3c.png)
> 
> The problem seems to be in [here](https://github.com/Artado-Project/artadosearch/blob/9730a1d2809475e968b4fd3a055453f10067add9/artadosearch/css/panel.css#L54). It might be caused by overflow.

Problem solved, see my pull request.

**Comment by LinuxUsersLinuxMint** [comment]
> Bro just delete `display:block;` line.
> 
> `.row_info span { margin-right: auto; margin-left: auto; max-width: 150px; max-height: 20vw; overflow: hidden; text-overflow: ellipsis; }`

Thank you display: block; I deleted it and the problem probably went away.

**Comment by LinuxUsersLinuxMint** [comment]
> In Firefox-based browsers: ![image](https://user-images.githubusercontent.com/47920304/274711097-b446a4d6-7946-4e65-8057-68c093dfe186.png)
> 
> In Chromium-based browsers: ![workshop](https://user-images.githubusercontent.com/47920304/274711236-8a096551-9f31-4221-93f6-ca533f9aaa3c.png)
> 
> The problem seems to be in [here](https://github.com/Artado-Project/artadosearch/blob/9730a1d2809475e968b4fd3a055453f10067add9/artadosearch/css/panel.css#L54). It might be caused by overflow.

Problems in /js/test.js and /css/panel.css files have been resolved.
NOTE: Before accepting the pull request, please check the changes and provide feedback.

**Comment by ardatdev** [comment]
Issue seems to still exists. https://github.com/Artado-Project/artadosearch/pull/24 and https://github.com/Artado-Project/artadosearch/commit/f4a48a59cd2bf66a548cb63a463cd5b1b6d8f161 did not fixed this issue.
Chromium in Linux Mint (same issue exist on Brave too):
![image](https://github.com/Artado-Project/artadosearch/assets/47920304/7a8ae789-ce40-4b46-b23e-83c7e14182a5)

**Comment by Arnolxu** [comment]
> Issue seems to still exists. #24 and [f4a48a5](https://github.com/Artado-Project/artadosearch/commit/f4a48a59cd2bf66a548cb63a463cd5b1b6d8f161) did not fixed this issue. Chromium in Linux Mint (same issue exists on Brave too): ![image](https://user-images.githubusercontent.com/47920304/277149534-7a8ae789-ce40-4b46-b23e-83c7e14182a5.png)

Looks like we forgot to include the fix in 357ce21d555e332c32936e2fb68718f70b089200 😳

**Comment by LinuxUsersLinuxMint** [comment]
:) I'm glad the problem was solved. I am once again proud of myself and you.
@ardatdev  @Arnolxu

By the way, @artadev I tried to join your discord server, but it asks for phone number verification, can you remove this (I really want to join your server).
